fix(ci-lint): fix some errors to exec rightly
- remove spell check by cSpell
- add header
- usee regex to check error

diff --git a/.github/workflows/ci-lint.yaml b/.github/workflows/ci-lint.yaml
--- a/.github/workflows/ci-lint.yaml
+++ b/.github/workflows/ci-lint.yaml
@@ -1,4 +1,12 @@
-name: pnpm Script CI
+# src: .github/workflows/ci-lint.yaml
+# @(#) : CI's lint definition using pnpm
+#
+# Copyright (c) 2025 atsushifx <http://github.com/atsushifx>
+#
+# This software is released under the MIT License.
+# https://opensource.org/licenses/MIT
+
+name: CI lint using pnpm
 
 on:
   push:
@@ -35,14 +43,13 @@ jobs:
         run: |
           set -o pipefail
           pnpm run lint 2>&1 | tee lint-report.txt
-          pnpm run lint:types 2>&1 | tee -a lint-report.txt
-          pnpm run check:spells 2>&1 | tee -a lint-report.txt
+          pnpm run lint:types 2>&1 | tee lint-report.txt
 
       - name: Check for errors or warnings in report
         id: lint_check
         run: |
           upload_report=false
-          if grep -q 'error' lint-report.txt; then
+          if grep -E '[1-9][0-9]* errors)?' lint-report.txt; then
             echo "errors_found=true" >> $GITHUB_OUTPUT
             upload_report=true
           else
@@ -53,15 +60,15 @@ jobs:
           fi
           echo "upload_report=$upload_report" >> $GITHUB_OUTPUT
 
-      - name: Fail on errors
-        if: steps.lint_check.outputs.errors_found == 'true'
-        run: |
-          echo "❌ Lint errors found!"
-          exit 1
-
       - name: Upload lint report (if problems found)
         if: steps.lint_check.outputs.upload_report == 'true'
         uses: actions/upload-artifact@v4
         with:
           name: lint-report
           path: lint-report.txt
+
+      - name: Fail on errors
+        if: steps.lint_check.outputs.errors_found == 'true'
+        run: |
+          echo "❌ Lint errors found!"
+          exit 1
